// export * from '@src/components/index'; // Re-export all components and types from the components index file

export {
  Alert,
  Badge,
  Button,
  Card,
  Dropdown,
  Modal,
  Tabs,
  TextMarco,
  Tooltip,
  Toast,
  IconButton,
} from '@src/components';
export type {
  AlertProps,
  AlertType,
  BadgeProps,
  BadgeVariant,
  ButtonProps,
  ButtonVariant,
  CardProps,
  DropdownProps,
  ModalProps,
  Tab,
  TabsProps,
  TextMarcoProps,
  TextMarcoVariant,
  ToastProps,
  ToastVariant,
  TooltipProps,
  IconButtonProps,
  IconButtonSize,
  IconButtonVariant,
} from '@src/components';
